### ISSUE TITLE
Minimize the IPython javascript libraries for kernels

### ISSUE THREAD

**Issue by rgbkrk** [rgbkrk/atom-ipynb#1]
The javascript libraries for IPython have a lot of workarounds for different browsers, versions, etc. Those need cleaned out.

Additionally, there are requirements that make less sense in atom, such as jQuery:

```
Failed to activate package named 'ipynb' ReferenceError: $ is not defined
  at [object Object].Kernel.bind_events (/Users/kyle6475/.atom/packages/ipynb/lib/IPython/combined.js:877:9)
  at new Kernel (/Users/kyle6475/.atom/packages/ipynb/lib/IPython/combined.js:853:14)
  at Object.<anonymous> (/Users/kyle6475/.atom/packages/ipynb/lib/ipynb.coffee:9:14)
  at Object.<anonymous> (/Users/kyle6475/.atom/packages/ipynb/lib/ipynb.coffee:1:1)
  at Module._compile (module.js:455:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:64:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)

... truncated ...
```

**Comment by rgbkrk** [comment]
We'll stop going this route and do this cleanly with `zmq`.
