### ISSUE TITLE
Failed to activate the ipynb package

### ISSUE THREAD

**Issue by martinzh** [rgbkrk/atom-ipynb#3]
[Enter steps to reproduce below:]
1. Just updated de ipynb package before updating atom to 0.201.0
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ipynb](https://github.com/rgbkrk/atom-ipynb) package, v0.1.1
### Stack Trace

Failed to activate the ipynb package

```
At 0 is not a valid selector in /Users/martinzh/.atom/packages/ipynb/package.json

SyntaxError: 0 is not a valid selector in /Users/martinzh/.atom/packages/ipynb/package.json
    at exports.validateSelector (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/clear-cut/index.js:115:19)
    at CommandRegistry.module.exports.CommandRegistry.add (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:44:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:753:70
    at Package.module.exports.Package.subscribeToActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:782:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:217:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at /Users/martinzh/.atom/packages/ipynb/package.json:1:1
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-alignment, v0.12.1
autocomplete-clang, v0.7.0
git-diff-details, v0.18.0
language-arduino, v0.2.1
language-csharp, v0.5.0
language-ipynb, v1.3.0
language-julia, v2.0.0
language-latex, v0.6.1
latex, v0.24.0
markdown-preview-plus, v1.4.0
minimap, v4.9.0
minimap-git-diff, v4.1.3
monokai, v0.14.0
processing-language, v0.1.0

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
Howdy!

I'd suggest using the [Hydrogen](https://github.com/willwhitney/hydrogen) package. It provides clean support across Jupyter kernels. This package may morph into something else but in its current state was a hack with websockets and the IPython JS.
